INSERT INTO `instansis` (`instansi`, `website`) VALUES
('Dinas Penanaman Modal dan Pelayanan Terpadu Satu Pintu Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Perindustrian dan Perdagangan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Perpustakaan dan Kearsipan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Kehutanan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Peternakan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Perumahan Rakyat, Kawasan Permukiman dan Cipta Karya Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Energi dan Sumber Daya Mineral Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Sosial Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Penanggulangan Bencana Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Kepemudaan dan Olahraga Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Pekerjaan Umum dan Bina Marga Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Penelitian dan Pengembangan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Lingkungan Hidup Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Pemberdayaan Perempuan, Perlindungan Anak dan Kependudukan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Pertanian dan Ketahanan Pangan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Kepegawaian Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Perkebunan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Kesehatan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Humas dan Protokol Sekretariat Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Umum Sekretariat Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Organisasi Sekretariat Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Administrasi Pembangunan Sekretariat Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Hukum Sekretariat Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Administrasi Kesejahteraan Sosial Sekretariat Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Adm. Pemerintahan dan Otoda Sekretariat Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Adm. Perekonomian Sekretariat Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Biro Adm. Sumber Daya Alam Sekretariat Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Kesatuan Bangsa dan Politik Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Pendidikan dan Pelatihan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Penghubung Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Perencanaan Pembangunan Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Pendapatan Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Pengelola Keuangan dan Aset Daerah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Komunikasi dan Informatika Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Pemberdayaan Masyarakat dan Desa Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Tenaga Kerja dan Transmigrasi Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Pendidikan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Koperasi, Usaha Kecil dan Menengah Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Kebudayaan dan Pariwisata Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Kelautan dan Perikanan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Pekerjaan Umum Sumber Daya Air Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Dinas Perhubungan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Inspektorat Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Satuan Polisi Pamong Praja Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Sekretariat DPRD Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('RSUD dr. Saiful Anwar Malang Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('RSUD dr. Soedono Madiun Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('RSUD dr. Soetomo Surabaya Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('RSUD Haji Surabaya Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Koordinasi Wilayah Pembangunan dan Pemerintahan I Madiun Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Koordinasi Wilayah Pembangunan dan Pemerintahan II Bojonegoro Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Koordinasi Wilayah Pembangunan dan Pemerintahan III Malang Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Koordinasi Wilayah Pembangunan dan Pemerintahan IV Pamekasan Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Badan Koordinasi Wilayah Pembangunan dan Pemerintahan V Jember Provinsi Jawa Timur', 'http://www.jatimprov.go.id/'),
('Kabupaten Madiun', 'http://madiunkab.go.id'),
('Kabupaten Magetan', 'http://www.magetankab.go.id'),
('Kabupaten Pacitan', 'http://www.pacitankab.go.id'),
('Kabupaten Ponorogo', 'http://www.ponorogo.go.id'),
('Kabupaten Ngawi', '	http://www.ngawikab.go.id'),
('Kabupaten Trenggalek', 'http://www.trenggalekkab.go.id'),
('Kabupaten Tulungagung', 'http://www.tulungagung.go.id'),
('Kabupaten Blitar', 'http://www.blitarkab.go.id'),
('Kabupaten Nganjuk', 'http://www.nganjukkab.go.id'),
('Kabupaten Bojonegoro', 'http://bojonegorokab.go.id'),
('Kabupaten Tuban', '	http://www.tubankab.go.id'),
('Kabupaten Mojokerto', '	http://www.mojokertokab.go.id'),
('Kabupaten Kediri', 'http://www.kedirikab.go.id'),
('Kabupaten Jombang', 'http://www.jombangkab.go.id'),
('Kabupaten Lamongan', 'http://www.lamongankab.go.id'),
('Kabupaten Malang', 'http://www.malangkab.go.id'),
('Kabupaten Pasuruan', 'http://www.pasuruankab.go.id'),
('Kabupaten Probolinggo', 'http://www.probolinggokab.go.id'),
('Kabupaten Lumajang', 'http://www.lumajangkab.go.id'),
('Kabupaten Jember', 'http://www.jemberkab.go.id'),
('Kabupaten Bondowoso', '	http://www.bondowosokab.go.id'),
('Kabupaten Situbondo', '	http://sv.situbondokab.go.id'),
('Kabupaten Banyuwangi', 'http://www.banyuwangikab.go.id'),
('Kabupaten Sidoarjo', 'http://www.sidoarjokab.go.id'),
('Kabupaten Gresik', 'http://www.gresikkab.go.id'),
('Kabupaten Bangkalan', '	http://www.bangkalankab.go.id'),
('Kabupaten Sampang', 'http://www.sampangkab.go.id'),
('Kabupaten Pamekasan', '	http://www.pamekasankab.go.id'),
('Kabupaten Sumenep', 'http://www.sumenepkab.go.id'),
('Kota Madiun', '	http://www.madiunkota.go.id'),
('Kota Blitar', '	http://www.blitarkota.go.id'),
('Kota Mojokerto', 'http://www.mojokertokota.go.id'),
('Kota Kediri', '	http://www.kedirikota.go.id'),
('Kota Malang', '	http://www.malangkota.go.id'),
('Kota Batu', 'http://www.batukota.go.id'),
('Kota Pasuruan', 'http://www.pasuruankota.go.id'),
('Kota Probolinggo', 'http://www.probolinggokab.go.id'),
('Kota Surabaya', 'http://www.surabaya.go.id');

